
services:
  app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=1000
      - NEXT_HMR_POLL_INTERVAL=1000
    command:
      - sh
      - -c
      - npm install && npm run dev-without-turbo
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-root}'
      MYSQL_DATABASE: '${MYSQL_DATABASE:-koray_prod}'
      MYSQL_USER: '${MYSQL_USER:-root}'
  adminer:
    container_name: adminer
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=500M
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
